version: '3.7'

services:
    #   api:
    #     restart: unless-stopped
    #     image: api:latest
    #     ports:
    #       - 4000:4000
    #     volumes:
    #       - ./api:/user/src/app
    #     depends_on:
    #       - mongo

    TSG:
        container_name: TSG
        image: tsg:dev
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - target: 3000 # the port inside the container
              published: 3000 # the publicly exposed port
              protocol: tcp # the port protocol (tcp or udp)
              mode: bridge # bridge networks are used to connect multiple containers together
        volumes:
            - .:/usr/src/app
        # depends_on:
        #     - api

    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017:27017

volumes:
    mongo_data:
