version: "3.7"

networks:
  tsg-network:
    driver: bridge

volumes:
  mongo_data:

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tsgpassword
      MONGO_INITDB_DATABSE: tsg
    labels:
      NAME: "mongodb"
    networks:
      - tsg-network
    volumes:
      - mongo_data:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: bridge

  tsg:
    container_name: tsg
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - tsg-api
    labels:
      NAME: "tsg"
    networks:
      - tsg-network
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: bridge

  tsg-api:
    container_name: tsg-api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    depends_on:
      - mongodb
    labels:
      NAME: "tsg api"
    networks:
      - tsg-network
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
        mode: bridge
